
import { ArabicWord, Surah } from './types';

export const JUZ_30_SURAHS: Surah[] = [
  { number: 78, name: "النبا", transliteration: "An-Naba", translation: "Berita Besar", totalVerses: 40, revelationType: 'Meccan' },
  { number: 79, name: "النازعات", transliteration: "An-Nazi'at", translation: "Malaikat-Malaikat Yang Mencabut", totalVerses: 46, revelationType: 'Meccan' },
  { number: 80, name: "عبس", transliteration: "Abasa", translation: "Ia Bermuka Masam", totalVerses: 42, revelationType: 'Meccan' },
  { number: 81, name: "التكوير", transliteration: "At-Takwir", translation: "Menggulung", totalVerses: 29, revelationType: 'Meccan' },
  { number: 82, name: "الانفطار", transliteration: "Al-Infitar", translation: "Terbelah", totalVerses: 19, revelationType: 'Meccan' },
  { number: 83, name: "المطففين", transliteration: "Al-Mutaffifin", translation: "Orang-Orang Yang Curang", totalVerses: 36, revelationType: 'Meccan' },
  { number: 84, name: "الانشقاق", transliteration: "Al-Inshiqaq", translation: "Terbelah", totalVerses: 25, revelationType: 'Meccan' },
  { number: 85, name: "البروج", transliteration: "Al-Buruj", translation: "Gugusan Bintang", totalVerses: 22, revelationType: 'Meccan' },
  { number: 86, name: "الطارق", transliteration: "At-Tariq", translation: "Yang Datang Di Malam Hari", totalVerses: 17, revelationType: 'Meccan' },
  { number: 87, name: "الأعلى", transliteration: "Al-A'la", translation: "Yang Paling Tinggi", totalVerses: 19, revelationType: 'Meccan' },
  { number: 88, name: "الغاشية", transliteration: "Al-Ghashiyah", translation: "Hari Pembalasan", totalVerses: 26, revelationType: 'Meccan' },
  { number: 89, name: "الفجر", transliteration: "Al-Fajr", translation: "Fajar", totalVerses: 30, revelationType: 'Meccan' },
  { number: 90, name: "البلد", transliteration: "Al-Balad", translation: "Negeri", totalVerses: 20, revelationType: 'Meccan' },
  { number: 91, name: "الشمس", transliteration: "Ash-Shams", translation: "Matahari", totalVerses: 15, revelationType: 'Meccan' },
  { number: 92, name: "الليل", transliteration: "Al-Layl", translation: "Malam", totalVerses: 21, revelationType: 'Meccan' },
  { number: 93, name: "الضحى", transliteration: "Ad-Duha", translation: "Waktu Matahari Sepenggalah Naik", totalVerses: 11, revelationType: 'Meccan' },
  { number: 94, name: "الشرح", transliteration: "Ash-Sharh", translation: "Melapangkan", totalVerses: 8, revelationType: 'Meccan' },
  { number: 95, name: "التين", transliteration: "At-Tin", translation: "Buah Tin", totalVerses: 8, revelationType: 'Meccan' },
  { number: 96, name: "العلق", transliteration: "Al-Alaq", translation: "Segumpal Darah", totalVerses: 19, revelationType: 'Meccan' },
  { number: 97, name: "القدر", transliteration: "Al-Qadr", translation: "Kemuliaan", totalVerses: 5, revelationType: 'Meccan' },
  { number: 98, name: "البينة", transliteration: "Al-Bayyinah", translation: "Pembuktian", totalVerses: 8, revelationType: 'Medinan' },
  { number: 99, name: "الزلزلة", transliteration: "Az-Zalzalah", translation: "Kegoncangan", totalVerses: 8, revelationType: 'Medinan' },
  { number: 100, name: "العاديات", transliteration: "Al-Adiyat", translation: "Kuda Perang Yang Berlari Kencang", totalVerses: 11, revelationType: 'Meccan' },
  { number: 101, name: "القارعة", transliteration: "Al-Qari'ah", translation: "Hari Kiamat", totalVerses: 11, revelationType: 'Meccan' },
  { number: 102, name: "التكاثر", transliteration: "At-Takathur", translation: "Bermegah-megahan", totalVerses: 8, revelationType: 'Meccan' },
  { number: 103, name: "العصر", transliteration: "Al-Asr", translation: "Masa", totalVerses: 3, revelationType: 'Meccan' },
  { number: 104, name: "الهمزة", transliteration: "Al-Humazah", translation: "Pengumpat", totalVerses: 9, revelationType: 'Meccan' },
  { number: 105, name: "الفيل", transliteration: "Al-Fil", translation: "Gajah", totalVerses: 5, revelationType: 'Meccan' },
  { number: 106, name: "قريش", transliteration: "Quraish", translation: "Suku Quraisy", totalVerses: 4, revelationType: 'Meccan' },
  { number: 107, name: "الماعون", transliteration: "Al-Ma'un", translation: "Barang-barang Yang Berguna", totalVerses: 7, revelationType: 'Meccan' },
  { number: 108, name: "الكوثر", transliteration: "Al-Kawthar", translation: "Nikmat Yang Banyak", totalVerses: 3, revelationType: 'Meccan' },
  { number: 109, name: "الكافرون", transliteration: "Al-Kafirun", translation: "Orang-orang Kafir", totalVerses: 6, revelationType: 'Meccan' },
  { number: 110, name: "النصر", transliteration: "An-Nasr", translation: "Pertolongan", totalVerses: 3, revelationType: 'Medinan' },
  { number: 111, name: "المسد", transliteration: "Al-Masad", translation: "Gejolak Api", totalVerses: 5, revelationType: 'Meccan' },
  { number: 112, name: "الإخلاص", transliteration: "Al-Ikhlas", translation: "Ikhlas", totalVerses: 4, revelationType: 'Meccan' },
  { number: 113, name: "الفلق", transliteration: "Al-Falaq", translation: "Waktu Subuh", totalVerses: 5, revelationType: 'Meccan' },
  { number: 114, name: "الناس", transliteration: "An-Nas", translation: "Manusia", totalVerses: 6, revelationType: 'Meccan' },
];

export const ARABIC_VOCAB: ArabicWord[] = [
  { arabic: "تُفَّاحَةٌ", latin: "Tuffahatun", meaning: "Apel", category: "Buah", image: "https://picsum.photos/seed/apple/200/200" },
  { arabic: "قِطٌّ", latin: "Qittun", meaning: "Kucing", category: "Hewan", image: "https://picsum.photos/seed/cat/200/200" },
  { arabic: "كِتَابٌ", latin: "Kitabun", meaning: "Buku", category: "Benda", image: "https://picsum.photos/seed/book/200/200" },
  { arabic: "بَيْتٌ", latin: "Baytun", meaning: "Rumah", category: "Benda", image: "https://picsum.photos/seed/house/200/200" },
  { arabic: "أَبٌ", latin: "Abun", meaning: "Ayah", category: "Keluarga", image: "https://picsum.photos/seed/father/200/200" },
  { arabic: "أُمٌّ", latin: "Ummun", meaning: "Ibu", category: "Keluarga", image: "https://picsum.photos/seed/mother/200/200" },
  { arabic: "سَيَّارَةٌ", latin: "Sayyaratun", meaning: "Mobil", category: "Kendaraan", image: "https://picsum.photos/seed/car/200/200" },
  { arabic: "مَدْرَسَةٌ", latin: "Madrasatun", meaning: "Sekolah", category: "Tempat", image: "https://picsum.photos/seed/school/200/200" },
];
