
import { ArabicWord, Surah, QuizQuestion, DailyPrayer } from './types';

export const JUZ_30_SURAHS: Surah[] = [
  { number: 78, name: "النبا", transliteration: "An-Naba", translation: "Berita Besar", totalVerses: 40, revelationType: 'Meccan' },
  { number: 79, name: "النازعات", transliteration: "An-Nazi'at", translation: "Malaikat-Malaikat Yang Mencabut", totalVerses: 46, revelationType: 'Meccan' },
  { number: 80, name: "عبس", transliteration: "Abasa", translation: "Ia Bermuka Masam", totalVerses: 42, revelationType: 'Meccan' },
  { number: 81, name: "التكوير", transliteration: "At-Takwir", translation: "Menggulung", totalVerses: 29, revelationType: 'Meccan' },
  { number: 82, name: "الانفطار", transliteration: "Al-Infitar", translation: "Terbelah", totalVerses: 19, revelationType: 'Meccan' },
  { number: 83, name: "المطففين", transliteration: "Al-Mutaffifin", translation: "Orang-Orang Yang Curang", totalVerses: 36, revelationType: 'Meccan' },
  { number: 84, name: "الانشقاق", transliteration: "Al-Inshiqaq", translation: "Terbelah", totalVerses: 25, revelationType: 'Meccan' },
  { number: 85, name: "البروج", transliteration: "Al-Buruj", translation: "Gugusan Bintang", totalVerses: 22, revelationType: 'Meccan' },
  { number: 86, name: "الطارق", transliteration: "At-Tariq", translation: "Yang Datang Di Malam Hari", totalVerses: 17, revelationType: 'Meccan' },
  { number: 87, name: "الأعلى", transliteration: "Al-A'la", translation: "Yang Paling Tinggi", totalVerses: 19, revelationType: 'Meccan' },
  { number: 88, name: "الغاشية", transliteration: "Al-Ghashiyah", translation: "Hari Pembalasan", totalVerses: 26, revelationType: 'Meccan' },
  { number: 89, name: "الفجر", transliteration: "Al-Fajr", translation: "Fajar", totalVerses: 30, revelationType: 'Meccan' },
  { number: 90, name: "البلد", transliteration: "Al-Balad", translation: "Negeri", totalVerses: 20, revelationType: 'Meccan' },
  { number: 91, name: "الشمس", transliteration: "Ash-Shams", translation: "Matahari", totalVerses: 15, revelationType: 'Meccan' },
  { number: 92, name: "الليل", transliteration: "Al-Layl", translation: "Malam", totalVerses: 21, revelationType: 'Meccan' },
  { number: 93, name: "الضحى", transliteration: "Ad-Duha", translation: "Waktu Matahari Sepenggalah Naik", totalVerses: 11, revelationType: 'Meccan' },
  { number: 94, name: "الشرح", transliteration: "Ash-Sharh", translation: "Melapangkan", totalVerses: 8, revelationType: 'Meccan' },
  { number: 95, name: "التين", transliteration: "At-Tin", translation: "Buah Tin", totalVerses: 8, revelationType: 'Meccan' },
  { number: 96, name: "العلق", transliteration: "Al-Alaq", translation: "Segumpal Darah", totalVerses: 19, revelationType: 'Meccan' },
  { number: 97, name: "القدر", transliteration: "Al-Qadr", translation: "Kemuliaan", totalVerses: 5, revelationType: 'Meccan' },
  { number: 98, name: "البينة", transliteration: "Al-Bayyinah", translation: "Pembuktian", totalVerses: 8, revelationType: 'Medinan' },
  { number: 99, name: "الزلزلة", transliteration: "Az-Zalzalah", translation: "Kegoncangan", totalVerses: 8, revelationType: 'Medinan' },
  { number: 100, name: "العاديات", transliteration: "Al-Adiyat", translation: "Kuda Perang Yang Berlari Kencang", totalVerses: 11, revelationType: 'Meccan' },
  { number: 101, name: "القارعة", transliteration: "Al-Qari'ah", translation: "Hari Kiamat", totalVerses: 11, revelationType: 'Meccan' },
  { number: 102, name: "التكاثر", transliteration: "At-Takathur", translation: "Bermegah-megahan", totalVerses: 8, revelationType: 'Meccan' },
  { number: 103, name: "العصر", transliteration: "Al-Asr", translation: "Masa", totalVerses: 3, revelationType: 'Meccan' },
  { number: 104, name: "الهمزة", transliteration: "Al-Humazah", translation: "Pengumpat", totalVerses: 9, revelationType: 'Meccan' },
  { number: 105, name: "الفيل", transliteration: "Al-Fil", translation: "Gajah", totalVerses: 5, revelationType: 'Meccan' },
  { number: 106, name: "قريش", transliteration: "Quraish", translation: "Suku Quraisy", totalVerses: 4, revelationType: 'Meccan' },
  { number: 107, name: "الماعون", transliteration: "Al-Ma'un", translation: "Barang-barang Yang Berguna", totalVerses: 7, revelationType: 'Meccan' },
  { number: 108, name: "الكوثر", transliteration: "Al-Kawthar", translation: "Nikmat Yang Banyak", totalVerses: 3, revelationType: 'Meccan' },
  { number: 109, name: "الكافرون", transliteration: "Al-Kafirun", translation: "Orang-orang Kafir", totalVerses: 6, revelationType: 'Meccan' },
  { number: 110, name: "النصر", transliteration: "An-Nasr", translation: "Pertolongan", totalVerses: 3, revelationType: 'Medinan' },
  { number: 111, name: "المسد", transliteration: "Al-Masad", translation: "Gejolak Api", totalVerses: 5, revelationType: 'Meccan' },
  { number: 112, name: "الإخلاص", transliteration: "Al-Ikhlas", translation: "Ikhlas", totalVerses: 4, revelationType: 'Meccan' },
  { number: 113, name: "الفلق", transliteration: "Al-Falaq", translation: "Waktu Subuh", totalVerses: 5, revelationType: 'Meccan' },
  { number: 114, name: "الناس", transliteration: "An-Nas", translation: "Manusia", totalVerses: 6, revelationType: 'Meccan' },
];

export const DAILY_PRAYERS: DailyPrayer[] = [
  {
    id: 'bangun-tidur',
    title: 'Doa Bangun Tidur',
    arabic: 'اَلْحَمْدُ لِلّٰهِ الَّذِيْ أَحْيَانَا بَعْدَ مَا أَمَاتَنَا وَإِلَيْهِ النُّشُوْرُ',
    latin: 'Alhamdu lillahil ladzii ahyaanaa ba\'da maa amaatanaa wa ilaihin nusyuur.',
    translation: 'Segala puji bagi Allah yang menghidupkan kami setelah mematikan kami dan kepada-Nya kami kembali.',
    imagePrompt: 'A cute kid waking up happily in a cozy bed with sun shining through window'
  },
  {
    id: 'masuk-wc',
    title: 'Doa Masuk Kamar Mandi',
    arabic: 'اللّٰهُمَّ إِنِّيْ أَعُوْذُ بِكَ مِنَ الْخُبُثِ وَالْخَبَائِثِ',
    latin: 'Alloohumma innii a\'uudzu bika minal khubutsi wal khobaaits.',
    translation: 'Ya Allah, aku berlindung pada-Mu dari godaan setan laki-laki dan setan perempuan.',
    imagePrompt: 'A cute kid entering a clean bathroom'
  },
  {
    id: 'keluar-wc',
    title: 'Doa Keluar Kamar Mandi',
    arabic: 'غُفْرَانَكَ الْحَمْدُ لِلّٰهِ الَّذِيْ أَذْهَبَ عَنِّى الْأَذَى وَعَافَانِيْ',
    latin: 'Ghufroonaka alhamdu lillaahil ladzii adzhaba \'annil adzaa wa \'aafaanii.',
    translation: 'Aku mohon ampunan-Mu. Segala puji bagi Allah yang telah menghilangkan kotoran dariku dan menyehatkanku.',
    imagePrompt: 'A cute kid exiting bathroom feeling fresh'
  },
  {
    id: 'sebelum-makan',
    title: 'Doa Sebelum Makan',
    arabic: 'اللّٰهُمَّ بَارِكْ لَنَا فِيْمَا رَزَقْتَنَا وَقِنَا عَذَابَ النَّارِ',
    latin: 'Alloohumma baarik lanaa fiimaa rozaqtanaa wa qinaa \'adzaaban naar.',
    translation: 'Ya Allah, berkahilah kami atas rezeki yang Engkau berikan dan peliharalah kami dari siksa api neraka.',
    imagePrompt: 'A cute kid sitting at a table with delicious healthy food'
  },
  {
    id: 'sesudah-makan',
    title: 'Doa Sesudah Makan',
    arabic: 'اَلْحَمْدُ لِلّٰهِ الَّذِيْ أَطْعَمَنَا وَسَقَانَا وَجَعَلَنَا مُسْلِمِيْنَ',
    latin: 'Alhamdu lillahil ladzii ath\'amanaa wa saqoonaa wa ja\'alanaa muslimiin.',
    translation: 'Segala puji bagi Allah yang telah memberi kami makan dan minum, serta menjadikan kami orang-orang muslim.',
    imagePrompt: 'A cute kid finishing meal with a happy smile'
  },
  {
    id: 'untuk-ortu',
    title: 'Doa Untuk Orang Tua',
    arabic: 'رَبِّ اغْفِرْ لِيْ وَلِوَالِدَيَّ وَارْحَمْهُمَا كَمَا رَبَّيَانِيْ صَغِيْرًا',
    latin: 'Rabbighfir lii waliwaalidayya warhamhumaa kamaa rabbayaanii shaghiiraa.',
    translation: 'Ya Tuhanku, ampunilah dosaku dan dosa kedua orang tuaku, dan sayangilah mereka sebagaimana mereka menyayangiku di waktu kecil.',
    imagePrompt: 'A cute kid hugging their parents with hearts'
  },
  {
    id: 'sebelum-tidur',
    title: 'Doa Sebelum Tidur',
    arabic: 'بِاسْمِكَ اللّٰهُمَّ أَحْيَا وَأَمُوْتُ',
    latin: 'Bismika alloohumma ahyaa wa amuutu.',
    translation: 'Dengan nama-Mu ya Allah, aku hidup dan aku mati.',
    imagePrompt: 'A cute kid sleeping peacefully under a starry sky blanket'
  }
];

export const STATIC_QUIZ_DATA: Record<string, QuizQuestion[]> = {
  'Hewan Lucu': [
    { question: "Apa bahasa Arabnya Kucing?", options: ["Qittun", "Kalbun", "Asadun", "Fiilun"], correctAnswer: "Qittun", arabicWord: "قِطٌّ", imagePrompt: "cute cartoon cat" },
    { question: "Apa bahasa Arabnya Gajah?", options: ["Jamalun", "Fiilun", "Asadun", "Arnabun"], correctAnswer: "Fiilun", arabicWord: "فِيْلٌ", imagePrompt: "cute cartoon elephant" },
    { question: "Apa bahasa Arabnya Singa?", options: ["Asadun", "Kalbun", "Qittun", "Jamalun"], correctAnswer: "Asadun", arabicWord: "أَسَدٌ", imagePrompt: "cute cartoon lion" },
    { question: "Apa bahasa Arabnya Kelinci?", options: ["Arnabun", "Kalbun", "Qittun", "Fiilun"], correctAnswer: "Arnabun", arabicWord: "أَرْنَبٌ", imagePrompt: "cute cartoon rabbit" },
    { question: "Apa bahasa Arabnya Unta?", options: ["Jamalun", "Kalbun", "Fiilun", "Asadun"], correctAnswer: "Jamalun", arabicWord: "جَمَلٌ", imagePrompt: "cute cartoon camel" },
    { question: "Apa bahasa Arabnya Burung?", options: ["Thairun", "Samakun", "Qittun", "Kalbun"], correctAnswer: "Thairun", arabicWord: "طَيْرٌ", imagePrompt: "cute cartoon bird" },
    { question: "Apa bahasa Arabnya Ikan?", options: ["Samakun", "Thairun", "Kalbun", "Arnabun"], correctAnswer: "Samakun", arabicWord: "سَمَكٌ", imagePrompt: "cute cartoon fish" },
    { question: "Apa bahasa Arabnya Kuda?", options: ["Hishaanun", "Fiilun", "Asadun", "Arnabun"], correctAnswer: "Hishaanun", arabicWord: "حِصَانٌ", imagePrompt: "cute cartoon horse" },
    { question: "Apa bahasa Arabnya Sapi?", options: ["Baqaratun", "Kalbun", "Jamalun", "Asadun"], correctAnswer: "Baqaratun", arabicWord: "بَقَرَةٌ", imagePrompt: "cute cartoon cow" },
    { question: "Apa bahasa Arabnya Monyet?", options: ["Qirdun", "Kalbun", "Asadun", "Fiilun"], correctAnswer: "Qirdun", arabicWord: "قِرْدٌ", imagePrompt: "cute cartoon monkey" },
  ],
  'Buah Segar': [
    { question: "Apa bahasa Arabnya Apel?", options: ["Tuffahatun", "Mauzun", "Burtuqalun", "Inabun"], correctAnswer: "Tuffahatun", arabicWord: "تُفَّاحَةٌ", imagePrompt: "shiny red apple cartoon" },
    { question: "Apa bahasa Arabnya Pisang?", options: ["Mauzun", "Tuffahatun", "Inabun", "Burtuqalun"], correctAnswer: "Mauzun", arabicWord: "مَوْزٌ", imagePrompt: "yellow banana cartoon" },
    { question: "Apa bahasa Arabnya Jeruk?", options: ["Burtuqalun", "Mauzun", "Tuffahatun", "Inabun"], correctAnswer: "Burtuqalun", arabicWord: "بُرْتُقَالٌ", imagePrompt: "fresh orange fruit cartoon" },
    { question: "Apa bahasa Arabnya Anggur?", options: ["Inabun", "Mauzun", "Tuffahatun", "Burtuqalun"], correctAnswer: "Inabun", arabicWord: "عِنَبٌ", imagePrompt: "bunch of purple grapes cartoon" },
    { question: "Apa bahasa Arabnya Semangka?", options: ["Bitthikhun", "Mauzun", "Tuffahatun", "Inabun"], correctAnswer: "Bitthikhun", arabicWord: "بِطِّيْخٌ", imagePrompt: "watermelon slice cartoon" },
    { question: "Apa bahasa Arabnya Kurma?", options: ["Tamrun", "Mauzun", "Tuffahatun", "Inabun"], correctAnswer: "Tamrun", arabicWord: "تَمْرٌ", imagePrompt: "dates fruit cartoon" },
    { question: "Apa bahasa Arabnya Nanas?", options: ["Ananasun", "Mauzun", "Tuffahatun", "Inabun"], correctAnswer: "Ananasun", arabicWord: "أَنَانَاسٌ", imagePrompt: "pineapple cartoon" },
    { question: "Apa bahasa Arabnya Delima?", options: ["Rummaanun", "Mauzun", "Tuffahatun", "Inabun"], correctAnswer: "Rummaanun", arabicWord: "رُمَّانٌ", imagePrompt: "pomegranate cartoon" },
    { question: "Apa bahasa Arabnya Stroberi?", options: ["Farawilatun", "Mauzun", "Tuffahatun", "Inabun"], correctAnswer: "Farawilatun", arabicWord: "فَرَاوِلَةٌ", imagePrompt: "strawberry cartoon" },
    { question: "Apa bahasa Arabnya Mangga?", options: ["Manju", "Mauzun", "Tuffahatun", "Inabun"], correctAnswer: "Manju", arabicWord: "مَنْجُو", imagePrompt: "mango fruit cartoon" },
  ],
  'Benda di Rumah': [
    { question: "Apa bahasa Arabnya Pintu?", options: ["Baabun", "Nafidzatun", "Kursiyyun", "Maktabun"], correctAnswer: "Baabun", arabicWord: "بَابٌ", imagePrompt: "wooden door cartoon" },
    { question: "Apa bahasa Arabnya Jendela?", options: ["Nafidzatun", "Baabun", "Kursiyyun", "Sariirun"], correctAnswer: "Nafidzatun", arabicWord: "نَافِذَةٌ", imagePrompt: "open window cartoon" },
    { question: "Apa bahasa Arabnya Kursi?", options: ["Kursiyyun", "Maktabun", "Baabun", "Sariirun"], correctAnswer: "Kursiyyun", arabicWord: "كُرْسِيٌّ", imagePrompt: "wooden chair cartoon" },
    { question: "Apa bahasa Arabnya Meja?", options: ["Maktabun", "Kursiyyun", "Baabun", "Sariirun"], correctAnswer: "Maktabun", arabicWord: "مَكْتَبٌ", imagePrompt: "desk table cartoon" },
    { question: "Apa bahasa Arabnya Tempat Tidur?", options: ["Sariirun", "Kursiyyun", "Maktabun", "Baabun"], correctAnswer: "Sariirun", arabicWord: "سَرِيْرٌ", imagePrompt: "cozy bed cartoon" },
    { question: "Apa bahasa Arabnya Lampu?", options: ["Misbaahun", "Baabun", "Kursiyyun", "Maktabun"], correctAnswer: "Misbaahun", arabicWord: "مِصْبَاحٌ", imagePrompt: "desk lamp cartoon" },
    { question: "Apa bahasa Arabnya Kunci?", options: ["Miftahun", "Baabun", "Kursiyyun", "Maktabun"], correctAnswer: "Miftahun", arabicWord: "مِفْتَاحٌ", imagePrompt: "golden key cartoon" },
    { question: "Apa bahasa Arabnya Kipas Angin?", options: ["Mirwahatun", "Baabun", "Kursiyyun", "Maktabun"], correctAnswer: "Mirwahatun", arabicWord: "مِرْوَحَةٌ", imagePrompt: "electric fan cartoon" },
    { question: "Apa bahasa Arabnya Jam?", options: ["Saa'atun", "Baabun", "Kursiyyun", "Maktabun"], correctAnswer: "Saa'atun", arabicWord: "سَاعَةٌ", imagePrompt: "wall clock cartoon" },
    { question: "Apa bahasa Arabnya Telepon?", options: ["Haatifun", "Baabun", "Kursiyyun", "Maktabun"], correctAnswer: "Haatifun", arabicWord: "هَاتِفٌ", imagePrompt: "telephone cartoon" },
  ],
  'Anggota Keluarga': [
    { question: "Apa bahasa Arabnya Ayah?", options: ["Abun", "Ummun", "Akhun", "Ukhtun"], correctAnswer: "Abun", arabicWord: "أَبٌ", imagePrompt: "father cartoon" },
    { question: "Apa bahasa Arabnya Ibu?", options: ["Ummun", "Abun", "Akhun", "Ukhtun"], correctAnswer: "Ummun", arabicWord: "أُمٌّ", imagePrompt: "mother cartoon" },
    { question: "Apa bahasa Arabnya Saudara Laki-laki?", options: ["Akhun", "Ukhtun", "Abun", "Ummun"], correctAnswer: "Akhun", arabicWord: "أَخٌ", imagePrompt: "brother cartoon" },
    { question: "Apa bahasa Arabnya Saudara Perempuan?", options: ["Ukhtun", "Akhun", "Abun", "Ummun"], correctAnswer: "Ukhtun", arabicWord: "أُخْتٌ", imagePrompt: "sister cartoon" },
    { question: "Apa bahasa Arabnya Kakek?", options: ["Jaddun", "Jaddatun", "Abun", "Ummun"], correctAnswer: "Jaddun", arabicWord: "جَدٌّ", imagePrompt: "grandfather cartoon" },
    { question: "Apa bahasa Arabnya Nenek?", options: ["Jaddatun", "Jaddun", "Abun", "Ummun"], correctAnswer: "Jaddatun", arabicWord: "جَدَّةٌ", imagePrompt: "grandmother cartoon" },
    { question: "Apa bahasa Arabnya Anak Laki-laki?", options: ["Waladun", "Bintun", "Abun", "Ummun"], correctAnswer: "Waladun", arabicWord: "وَلَدٌ", imagePrompt: "boy cartoon" },
    { question: "Apa bahasa Arabnya Anak Perempuan?", options: ["Bintun", "Waladun", "Abun", "Ummun"], correctAnswer: "Bintun", arabicWord: "بِنْتٌ", imagePrompt: "girl cartoon" },
    { question: "Apa bahasa Arabnya Paman?", options: ["Ammun", "Ammatun", "Abun", "Ummun"], correctAnswer: "Ammun", arabicWord: "عَمٌّ", imagePrompt: "uncle cartoon" },
    { question: "Apa bahasa Arabnya Bibi?", options: ["Ammatun", "Ammun", "Abun", "Ummun"], correctAnswer: "Ammatun", arabicWord: "عَمَّةٌ", imagePrompt: "aunt cartoon" },
  ],
  'Warna-warni': [
    { question: "Apa bahasa Arabnya Merah?", options: ["Ahmaru", "Azraqu", "Abhyadu", "Aswadu"], correctAnswer: "Ahmaru", arabicWord: "أَحْمَرُ", imagePrompt: "red color splash" },
    { question: "Apa bahasa Arabnya Biru?", options: ["Azraqu", "Ahmaru", "Akhdaru", "Asfaru"], correctAnswer: "Azraqu", arabicWord: "أَزْرَقُ", imagePrompt: "blue color splash" },
    { question: "Apa bahasa Arabnya Hijau?", options: ["Akhdaru", "Ahmaru", "Azraqu", "Asfaru"], correctAnswer: "Akhdaru", arabicWord: "أَخْضَرُ", imagePrompt: "green color splash" },
    { question: "Apa bahasa Arabnya Kuning?", options: ["Asfaru", "Ahmaru", "Azraqu", "Akhdaru"], correctAnswer: "Asfaru", arabicWord: "أَصْفَرُ", imagePrompt: "yellow color splash" },
    { question: "Apa bahasa Arabnya Putih?", options: ["Abhyadu", "Aswadu", "Ahmaru", "Azraqu"], correctAnswer: "Abhyadu", arabicWord: "أَبْيَضُ", imagePrompt: "white color splash" },
    { question: "Apa bahasa Arabnya Hitam?", options: ["Aswadu", "Abhyadu", "Ahmaru", "Azraqu"], correctAnswer: "Aswadu", arabicWord: "أَسْوَدُ", imagePrompt: "black color splash" },
    { question: "Apa bahasa Arabnya Cokelat?", options: ["Bunniyyun", "Ahmaru", "Azraqu", "Akhdaru"], correctAnswer: "Bunniyyun", arabicWord: "بُنِّيٌّ", imagePrompt: "brown color splash" },
    { question: "Apa bahasa Arabnya Oranye?", options: ["Burtuqaaliyyun", "Ahmaru", "Azraqu", "Akhdaru"], correctAnswer: "Burtuqaaliyyun", arabicWord: "بُرْتُقَالِيٌّ", imagePrompt: "orange color splash" },
    { question: "Apa bahasa Arabnya Merah Muda?", options: ["Wardiyyun", "Ahmaru", "Azraqu", "Akhdaru"], correctAnswer: "Wardiyyun", arabicWord: "وَرْدِيٌّ", imagePrompt: "pink color splash" },
    { question: "Apa bahasa Arabnya Ungu?", options: ["Banafsajiyyun", "Ahmaru", "Azraqu", "Akhdaru"], correctAnswer: "Banafsajiyyun", arabicWord: "بَنَفْسَجِيٌّ", imagePrompt: "purple color splash" },
  ],
  'Angka Arab': [
    { question: "Wahidun artinya?", options: ["1", "2", "3", "4"], correctAnswer: "1", arabicWord: "وَاحِدٌ", imagePrompt: "number 1 cartoon" },
    { question: "Itsnaini artinya?", options: ["2", "1", "3", "4"], correctAnswer: "2", arabicWord: "اِثْنَانِ", imagePrompt: "number 2 cartoon" },
    { question: "Tsalatsatun artinya?", options: ["3", "2", "1", "4"], correctAnswer: "3", arabicWord: "ثَلَاثَةٌ", imagePrompt: "number 3 cartoon" },
    { question: "Arba'atun artinya?", options: ["4", "3", "2", "1"], correctAnswer: "4", arabicWord: "أَرْبَعَةٌ", imagePrompt: "number 4 cartoon" },
    { question: "Khamsatun artinya?", options: ["5", "4", "3", "2"], correctAnswer: "5", arabicWord: "خَمْسَةٌ", imagePrompt: "number 5 cartoon" },
    { question: "Sittatun artinya?", options: ["6", "5", "4", "3"], correctAnswer: "6", arabicWord: "سِتَّةٌ", imagePrompt: "number 6 cartoon" },
    { question: "Sab'atun artinya?", options: ["7", "6", "5", "4"], correctAnswer: "7", arabicWord: "سَبْعَةٌ", imagePrompt: "number 7 cartoon" },
    { question: "Tsamaniyatun artinya?", options: ["8", "7", "6", "5"], correctAnswer: "8", arabicWord: "ثَمَانِيَةٌ", imagePrompt: "number 8 cartoon" },
    { question: "Tis'atun artinya?", options: ["9", "8", "7", "6"], correctAnswer: "9", arabicWord: "تِسْعَةٌ", imagePrompt: "number 9 cartoon" },
    { question: "Asyaratun artinya?", options: ["10", "9", "8", "7"], correctAnswer: "10", arabicWord: "عَشَرَةٌ", imagePrompt: "number 10 cartoon" },
  ],
  'Kendaraan': [
    { question: "Apa bahasa Arabnya Mobil?", options: ["Sayyaratun", "Darrajatun", "Thairatun", "Safinatun"], correctAnswer: "Sayyaratun", arabicWord: "سَيَّارَةٌ", imagePrompt: "colorful cute cartoon car" },
    { question: "Apa bahasa Arabnya Sepeda Motor?", options: ["Darrajatun Bukhariyyah", "Sayyaratun", "Hafilatun", "Qitharun"], correctAnswer: "Darrajatun Bukhariyyah", arabicWord: "دَرَّاجَةٌ بُخَارِيَّةٌ", imagePrompt: "cute cartoon motorcycle" },
    { question: "Apa bahasa Arabnya Pesawat Terbang?", options: ["Thairatun", "Sayyaratun", "Safinatun", "Darrajatun"], correctAnswer: "Thairatun", arabicWord: "طَائِرَةٌ", imagePrompt: "happy cute cartoon airplane" },
    { question: "Apa bahasa Arabnya Kapal Laut?", options: ["Safinatun", "Thairatun", "Hafilatun", "Sayyaratun"], correctAnswer: "Safinatun", arabicWord: "سَفِيْنَةٌ", imagePrompt: "big cute cartoon ship" },
    { question: "Apa bahasa Arabnya Bus?", options: ["Hafilatun", "Sayyaratun", "Qitharun", "Safinatun"], correctAnswer: "Hafilatun", arabicWord: "حَافِلَةٌ", imagePrompt: "yellow school bus cartoon" },
    { question: "Apa bahasa Arabnya Kereta Api?", options: ["Qitharun", "Hafilatun", "Safinatun", "Thairatun"], correctAnswer: "Qitharun", arabicWord: "قِطَارٌ", imagePrompt: "happy steam train cartoon" },
    { question: "Apa bahasa Arabnya Sepeda?", options: ["Darrajatun", "Sayyaratun", "Safinatun", "Hafilatun"], correctAnswer: "Darrajatun", arabicWord: "دَرَّاجَةٌ", imagePrompt: "little cute bicycle cartoon" },
    { question: "Apa bahasa Arabnya Ambulans?", options: ["Sayyaratun Is'af", "Hafilatun", "Qitharun", "Thairatun"], correctAnswer: "Sayyaratun Is'af", arabicWord: "سَيَّارَةُ إِسْعَافٍ", imagePrompt: "cute cartoon ambulance" },
    { question: "Apa bahasa Arabnya Truk?", options: ["Syahinah", "Sayyaratun", "Hafilatun", "Darrajatun"], correctAnswer: "Syahinah", arabicWord: "شَاحِنَةٌ", imagePrompt: "big cute toy truck" },
    { question: "Apa bahasa Arabnya Helikopter?", options: ["Mirowahiyyah", "Thairatun", "Safinatun", "Sayyaratun"], correctAnswer: "Mirowahiyyah", arabicWord: "مِرْوَحِيَّةٌ", imagePrompt: "cute cartoon helicopter" },
  ],
  'Pakaian': [
    { question: "Apa bahasa Arabnya Baju/Kemeja?", options: ["Qamishun", "Sirwalun", "Fustannun", "Hidza-un"], correctAnswer: "Qamishun", arabicWord: "قَمِيْصٌ", imagePrompt: "cute clean shirt cartoon" },
    { question: "Apa bahasa Arabnya Celana?", options: ["Sirwalun", "Qamishun", "Jaubrabun", "Khimarun"], correctAnswer: "Sirwalun", arabicWord: "سِرْوَالٌ", imagePrompt: "blue trousers cartoon" },
    { question: "Apa bahasa Arabnya Gaun?", options: ["Fustannun", "Qamishun", "Sirwalun", "Hidza-un"], correctAnswer: "Fustannun", arabicWord: "فُسْتَانٌ", imagePrompt: "pretty pink dress cartoon" },
    { question: "Apa bahasa Arabnya Sepatu?", options: ["Hidza-un", "Jaubrabun", "Qum'atun", "Nadzoratun"], correctAnswer: "Hidza-un", arabicWord: "حِذَاءٌ", imagePrompt: "cute pair of shoes cartoon" },
    { question: "Apa bahasa Arabnya Kaos Kaki?", options: ["Jaubrabun", "Hidza-un", "Khimarun", "Sirwalun"], correctAnswer: "Jaubrabun", arabicWord: "جَوْرَبٌ", imagePrompt: "colorful socks cartoon" },
    { question: "Apa bahasa Arabnya Topi?", options: ["Qubba'atun", "Nadzoratun", "Khimarun", "Qamishun"], correctAnswer: "Qubba'atun", arabicWord: "قُبَّعَةٌ", imagePrompt: "cool sun hat cartoon" },
    { question: "Apa bahasa Arabnya Jilbab/Kerudung?", options: ["Khimarun", "Jaubrabun", "Fustannun", "Sirwalun"], correctAnswer: "Khimarun", arabicWord: "خِمَارٌ", imagePrompt: "cute pink hijab cartoon" },
    { question: "Apa bahasa Arabnya Kacamata?", options: ["Nadzoratun", "Qubba'atun", "Hidza-un", "Qamishun"], correctAnswer: "Nadzoratun", arabicWord: "نَظَّارَةٌ", imagePrompt: "stylish glasses cartoon" },
    { question: "Apa bahasa Arabnya Jaket?", options: ["Sutratun", "Qamishun", "Sirwalun", "Fustannun"], correctAnswer: "Sutratun", arabicWord: "سُتْرَةٌ", imagePrompt: "warm winter jacket cartoon" },
    { question: "Apa bahasa Arabnya Sabuk?", options: ["Hizamun", "Hidza-un", "Qubba'atun", "Khimarun"], correctAnswer: "Hizamun", arabicWord: "حِزَامٌ", imagePrompt: "leather belt cartoon" },
  ],
  'Hobi & Olahraga': [
    { question: "Apa bahasa Arabnya Sepak Bola?", options: ["Kurratul Qadam", "Kurratu Sallah", "Sibahah", "Jar-yu"], correctAnswer: "Kurratul Qadam", arabicWord: "كُرَةُ الْقَدَمِ", imagePrompt: "soccer ball on grass cartoon" },
    { question: "Apa bahasa Arabnya Berenang?", options: ["Sibahah", "Kurratul Qadam", "Jar-yu", "Qiro-ah"], correctAnswer: "Sibahah", arabicWord: "سِبَاحَةٌ", imagePrompt: "cute kid swimming in pool" },
    { question: "Apa bahasa Arabnya Membaca?", options: ["Qiro-ah", "Kitabah", "Rasm", "Sibahah"], correctAnswer: "Qiro-ah", arabicWord: "قِرَاءَةٌ", imagePrompt: "cute kid reading a book" },
    { question: "Apa bahasa Arabnya Menulis?", options: ["Kitabah", "Qiro-ah", "Sibahah", "Kurratul Qadam"], correctAnswer: "Kitabah", arabicWord: "كِتَابَةٌ", imagePrompt: "cute kid writing with pencil" },
    { question: "Apa bahasa Arabnya Melukis?", options: ["Rasm", "Qiro-ah", "Kitabah", "Jar-yu"], correctAnswer: "Rasm", arabicWord: "رَسْمٌ", imagePrompt: "cute kid painting on canvas" },
    { question: "Apa bahasa Arabnya Lari?", options: ["Jar-yu", "Sibahah", "Kurratul Qadam", "Rasm"], correctAnswer: "Jar-yu", arabicWord: "جَرْيٌ", imagePrompt: "cute kid running happily" },
    { question: "Apa bahasa Arabnya Basket?", options: ["Kurratu Sallah", "Kurratul Qadam", "Sibahah", "Qiro-ah"], correctAnswer: "Kurratu Sallah", arabicWord: "كُرَةُ السَّلَّةِ", imagePrompt: "basketball and hoop cartoon" },
    { question: "Apa bahasa Arabnya Bulutangkis?", options: ["Risyah", "Kurratul Qadam", "Sibahah", "Jar-yu"], correctAnswer: "Risyah", arabicWord: "رِيْشَةٌ", imagePrompt: "shuttlecock and racket cartoon" },
    { question: "Apa bahasa Arabnya Memasak?", options: ["Thobkhun", "Qiro-ah", "Rasm", "Kitabah"], correctAnswer: "Thobkhun", arabicWord: "طَبْخٌ", imagePrompt: "cute chef kid cooking" },
    { question: "Apa bahasa Arabnya Bersepeda?", options: ["Rukubud Darrajah", "Sibahah", "Jar-yu", "Rasm"], correctAnswer: "Rukubud Darrajah", arabicWord: "رُكُوْبُ الدَّرَّاجَةِ", imagePrompt: "cute kid riding a bike" },
  ],
  'Alam & Cuaca': [
    { question: "Apa bahasa Arabnya Matahari?", options: ["Syamsun", "Qamarun", "Najmun", "Sama-un"], correctAnswer: "Syamsun", arabicWord: "شَمْسٌ", imagePrompt: "happy sun cartoon" },
    { question: "Apa bahasa Arabnya Bulan?", options: ["Qamarun", "Syamsun", "Ardun", "Jabalun"], correctAnswer: "Qamarun", arabicWord: "قَمَرٌ", imagePrompt: "crescent moon cartoon" },
    { question: "Apa bahasa Arabnya Bintang?", options: ["Najmun", "Qamarun", "Syamsun", "Sama-un"], correctAnswer: "Najmun", arabicWord: "نَجْمٌ", imagePrompt: "shining star cartoon" },
    { question: "Apa bahasa Arabnya Gunung?", options: ["Jabalun", "Ardun", "Sama-un", "Bahrun"], correctAnswer: "Jabalun", arabicWord: "جَبَلٌ", imagePrompt: "big green mountain cartoon" },
    { question: "Apa bahasa Arabnya Laut?", options: ["Bahrun", "Jabalun", "Sama-un", "Nahrun"], correctAnswer: "Bahrun", arabicWord: "بَحْرٌ", imagePrompt: "blue ocean with waves cartoon" },
    { question: "Apa bahasa Arabnya Sungai?", options: ["Nahrun", "Bahrun", "Jabalun", "Ardun"], correctAnswer: "Nahrun", arabicWord: "نَهْرٌ", imagePrompt: "winding river cartoon" },
    { question: "Apa bahasa Arabnya Hujan?", options: ["Matharun", "Sama-un", "Syamsun", "Sahabun"], correctAnswer: "Matharun", arabicWord: "مَطَرٌ", imagePrompt: "rain clouds and drops cartoon" },
    { question: "Apa bahasa Arabnya Awan?", options: ["Sahabun", "Matharun", "Syamsun", "Najmun"], correctAnswer: "Sahabun", arabicWord: "سَحَابٌ", imagePrompt: "fluffy white clouds cartoon" },
    { question: "Apa bahasa Arabnya Langit?", options: ["Sama-un", "Ardun", "Jabalun", "Bahrun"], correctAnswer: "Sama-un", arabicWord: "سَمَاءٌ", imagePrompt: "clear blue sky cartoon" },
    { question: "Apa bahasa Arabnya Pohon?", options: ["Syajaratun", "Jabalun", "Ardun", "Nahrun"], correctAnswer: "Syajaratun", arabicWord: "شَجَرَةٌ", imagePrompt: "big leafy tree cartoon" },
  ],
  'Profesi': [
    { question: "Apa bahasa Arabnya Dokter?", options: ["Thobiibun", "Mudarrisun", "Muhandisun", "Fallahun"], correctAnswer: "Thobiibun", arabicWord: "طَبِيْبٌ", imagePrompt: "cute cartoon doctor with stethoscope" },
    { question: "Apa bahasa Arabnya Guru?", options: ["Mudarrisun", "Thobiibun", "Thoyyarun", "Syurthiyyun"], correctAnswer: "Mudarrisun", arabicWord: "مُدَرِّسٌ", imagePrompt: "friendly teacher at blackboard cartoon" },
    { question: "Apa bahasa Arabnya Polisi?", options: ["Syurthiyyun", "Jundiyyun", "Thobiibun", "Mudarrisun"], correctAnswer: "Syurthiyyun", arabicWord: "شُرْطِيٌّ", imagePrompt: "cute police officer cartoon" },
    { question: "Apa bahasa Arabnya Pilot?", options: ["Thoyyarun", "Muhandisun", "Fallahun", "Tajirun"], correctAnswer: "Thoyyarun", arabicWord: "طَيَّارٌ", imagePrompt: "cute pilot in uniform cartoon" },
    { question: "Apa bahasa Arabnya Insinyur?", options: ["Muhandisun", "Tajirun", "Mudarrisun", "Thobiibun"], correctAnswer: "Muhandisun", arabicWord: "مُهَنْدِسٌ", imagePrompt: "cute engineer with hard hat cartoon" },
    { question: "Apa bahasa Arabnya Petani?", options: ["Fallahun", "Tajirun", "Thobiibun", "Mudarrisun"], correctAnswer: "Fallahun", arabicWord: "فَلَّاحٌ", imagePrompt: "happy farmer in the field cartoon" },
    { question: "Apa bahasa Arabnya Pedagang?", options: ["Tajirun", "Fallahun", "Muhandisun", "Thoyyarun"], correctAnswer: "Tajirun", arabicWord: "تَاجِرٌ", imagePrompt: "merchant in a shop cartoon" },
    { question: "Apa bahasa Arabnya Tentara?", options: ["Jundiyyun", "Syurthiyyun", "Thoyyarun", "Muhandisun"], correctAnswer: "Jundiyyun", arabicWord: "جُنْدِيٌّ", imagePrompt: "brave cute soldier cartoon" },
    { question: "Apa bahasa Arabnya Koki?", options: ["Thabbakhun", "Thobiibun", "Mudarrisun", "Tajirun"], correctAnswer: "Thabbakhun", arabicWord: "طَبَّاخٌ", imagePrompt: "chef kid with hat cartoon" },
    { question: "Apa bahasa Arabnya Nelayan?", options: ["Shoyyadun", "Fallahun", "Tajirun", "Syurthiyyun"], correctAnswer: "Shoyyadun", arabicWord: "صَيَّادٌ", imagePrompt: "fisherman with rod cartoon" },
  ],
  'Sekolah': [
    { question: "Apa bahasa Arabnya Buku?", options: ["Kitaabun", "Qolamun", "Mirasamatun", "Haqibatun"], correctAnswer: "Kitaabun", arabicWord: "كِتَابٌ", imagePrompt: "colorful textbook cartoon" },
    { question: "Apa bahasa Arabnya Pena/Pulpen?", options: ["Qolamun", "Kitaabun", "Mirasamatun", "Mishtharatun"], correctAnswer: "Qolamun", arabicWord: "قَلَمٌ", imagePrompt: "ink pen cartoon" },
    { question: "Apa bahasa Arabnya Pensil?", options: ["Mirasamatun", "Qolamun", "Kitaabun", "Mimhatun"], correctAnswer: "Mirasamatun", arabicWord: "مِرْسَمَةٌ", imagePrompt: "yellow pencil cartoon" },
    { question: "Apa bahasa Arabnya Tas?", options: ["Haqibatun", "Mimhatun", "Mishtharatun", "Kitaabun"], correctAnswer: "Haqibatun", arabicWord: "حَقِيْبَةٌ", imagePrompt: "school backpack cartoon" },
    { question: "Apa bahasa Arabnya Penggaris?", options: ["Mishtharatun", "Haqibatun", "Mimhatun", "Qolamun"], correctAnswer: "Mishtharatun", arabicWord: "مِسْطَرَةٌ", imagePrompt: "ruler tool cartoon" },
    { question: "Apa bahasa Arabnya Penghapus?", options: ["Mimhatun", "Mishtharatun", "Qolamun", "Kitaabun"], correctAnswer: "Mimhatun", arabicWord: "مِمْحَاةٌ", imagePrompt: "rubber eraser cartoon" },
    { question: "Apa bahasa Arabnya Sekolah?", options: ["Madrosatun", "Baitun", "Masjidun", "Mustasyfa"], correctAnswer: "Madrosatun", arabicWord: "مَدْرَسَةٌ", imagePrompt: "pretty school building cartoon" },
    { question: "Apa bahasa Arabnya Kelas?", options: ["Fashlun", "Madrosatun", "Maktabatun", "Saahatun"], correctAnswer: "Fashlun", arabicWord: "فَصْلٌ", imagePrompt: "bright classroom interior cartoon" },
    { question: "Apa bahasa Arabnya Perpustakaan?", options: ["Maktabatun", "Fashlun", "Madrosatun", "Baitun"], correctAnswer: "Maktabatun", arabicWord: "مَكْتَبَةٌ", imagePrompt: "library with bookshelves cartoon" },
    { question: "Apa bahasa Arabnya Papan Tulis?", options: ["Sabburotun", "Mimhatun", "Mishtharatun", "Kitaabun"], correctAnswer: "Sabburotun", arabicWord: "سَبُّوْرَةٌ", imagePrompt: "large blackboard cartoon" },
  ],
  'Makanan & Minuman': [
    { question: "Apa bahasa Arabnya Nasi?", options: ["Ruzzun", "Khubzun", "Labanun", "Ma-un"], correctAnswer: "Ruzzun", arabicWord: "رُزٌّ", imagePrompt: "bowl of white rice cartoon" },
    { question: "Apa bahasa Arabnya Roti?", options: ["Khubzun", "Ruzzun", "Sukkarun", "Shayun"], correctAnswer: "Khubzun", arabicWord: "خُبْزٌ", imagePrompt: "loaf of bread cartoon" },
    { question: "Apa bahasa Arabnya Air?", options: ["Ma-un", "Labanun", "Shayun", "Qahwatun"], correctAnswer: "Ma-un", arabicWord: "مَاءٌ", imagePrompt: "glass of water cartoon" },
    { question: "Apa bahasa Arabnya Susu?", options: ["Labanun", "Ma-un", "Shayun", "Qahwatun"], correctAnswer: "Labanun", arabicWord: "لَبَنٌ", imagePrompt: "carton of milk cartoon" },
    { question: "Apa bahasa Arabnya Teh?", options: ["Shayun", "Qahwatun", "Ma-un", "Labanun"], correctAnswer: "Shayun", arabicWord: "شَايٌ", imagePrompt: "cup of tea cartoon" },
    { question: "Apa bahasa Arabnya Kopi?", options: ["Qahwatun", "Shayun", "Ma-un", "Sukkarun"], correctAnswer: "Qahwatun", arabicWord: "قَهْوَةٌ", imagePrompt: "cup of coffee cartoon" },
    { question: "Apa bahasa Arabnya Gula?", options: ["Sukkarun", "Milhun", "Ruzzun", "Khubzun"], correctAnswer: "Sukkarun", arabicWord: "سُكَّرٌ", imagePrompt: "sugar cubes cartoon" },
    { question: "Apa bahasa Arabnya Garam?", options: ["Milhun", "Sukkarun", "Ruzzun", "Khubzun"], correctAnswer: "Milhun", arabicWord: "مِلْحٌ", imagePrompt: "salt shaker cartoon" },
    { question: "Apa bahasa Arabnya Daging?", options: ["Lahmun", "Samakun", "Dajajun", "Baidhun"], correctAnswer: "Lahmun", arabicWord: "لَحْمٌ", imagePrompt: "piece of steak meat cartoon" },
    { question: "Apa bahasa Arabnya Telur?", options: ["Baidhun", "Dajajun", "Samakun", "Lahmun"], correctAnswer: "Baidhun", arabicWord: "بَيْضٌ", imagePrompt: "boiled eggs cartoon" },
  ],
};
